version: 0.2
phases:
  install:
    commands:
    - npm install -g serverless@3.38.0
  build:
    commands:
    - echo == Stage = ${STAGE}
    - npm install --omit=dev
    - serverless deploy --stage ${STAGE}
