service: test-lambda-service-me
frameworkVersions: '3'

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    STAGE: ${self:provider.stage}
   
functions:
  users:
    handler: src/functions/users/handler.api
    events:
      - http:
          path: /users
          method: GET
          cors: true
